import type { CapivaraDefinition } from '@/lib/types';

export const CAPIVARA_IMAGES: Record<string, string> = {
  ara: '/capivaras/ara.png',
  ivi: '/capivaras/ivi.png',
  oka: '/capivaras/oka.png',
  yara: '/capivaras/yara.png',
  ayvu: '/capivaras/ayvu.png',
  mbae: '/capivaras/mbae.png',
  pora: '/capivaras/pora.png',
  tupa: '/capivaras/tupa.png',
};

export const CAPIVARAS: CapivaraDefinition[] = [
  {
    id: 'ara',
    name: 'ARA',
    fullName: 'ARA — Life & Time',
    description: 'Your day, before it begins.',
    longDescription:
      'ARA is always with you — managing your calendar, tracking the weather, setting reminders, taking notes, and speaking in your language. The foundation of your CAPIVAREX experience.',
    color: '#D4A017',
    price: 19.99,
    status: 'active',
    alwaysIncluded: true,
    capabilities: [
      { icon: '🗓️', name: 'Calendar', description: 'Sync and manage Google & Microsoft calendars' },
      { icon: '⏰', name: 'Reminders', description: 'Smart reminders with context and location' },
      { icon: '🌤️', name: 'Weather', description: 'Real-time weather and forecasts' },
      { icon: '📝', name: 'Notes', description: 'Voice and text notes, always searchable' },
      { icon: '🗣️', name: 'Voice', description: 'Talk to ARA naturally in any language' },
      { icon: '🌍', name: 'Translate', description: 'Real-time translation in 100+ languages' },
      { icon: '🔍', name: 'Research', description: 'Deep web research with cited sources' },
      { icon: '🗺️', name: 'Maps & Traffic', description: 'Navigation, commute alerts, leaving-now reminders' },
      { icon: '⏱️', name: 'Timer & Clock', description: 'Timers, world clocks, timezone conversions' },
      { icon: '📅', name: 'Meeting Prep', description: 'Auto-briefings before every meeting' },
      { icon: '📧', name: 'Email Briefing', description: 'Morning summary of your important emails — unread count, urgent flags, and key senders' },
    ],
  },
  {
    id: 'ivi',
    name: 'IVI',
    fullName: 'IVI — Finance & Crypto',
    description: 'Your financial intelligence.',
    longDescription:
      "IVI tracks your money so you don't have to. Stocks, crypto, expense tracking, and market insights — all in natural language.",
    color: '#2ECC71',
    price: 9.99,
    status: 'coming_soon',
    alwaysIncluded: false,
    capabilities: [
      { icon: '📈', name: 'Stocks', description: 'Real-time stock prices, charts, and alerts' },
      { icon: '₿', name: 'Crypto', description: 'Crypto portfolio tracking and market data' },
      { icon: '💳', name: 'Expenses', description: 'Expense tracking and spending insights' },
      { icon: '📰', name: 'Market News', description: 'Financial news filtered by your portfolio' },
    ],
  },
  {
    id: 'oka',
    name: 'OKA',
    fullName: 'OKA — Home & IoT',
    description: 'Your smart home command center.',
    longDescription:
      'OKA connects your home. Control lights, temperature, your connected car, and all IoT devices through a single voice command.',
    color: '#3498DB',
    price: 9.99,
    status: 'coming_soon',
    alwaysIncluded: false,
    capabilities: [
      { icon: '💡', name: 'Smart Lights', description: 'Control Philips Hue, LIFX, and more' },
      { icon: '🌡️', name: 'Climate', description: 'Thermostat and AC control' },
      { icon: '🚗', name: 'Connected Car', description: 'Vehicle status, lock/unlock, location' },
      { icon: '🏠', name: 'Home Scenes', description: 'Create and trigger custom home scenes' },
    ],
  },
  {
    id: 'yara',
    name: 'YARA',
    fullName: 'YARA — Travel & Mobility',
    description: 'Your travel companion.',
    longDescription:
      'YARA handles everything that moves. Flights, hotels, traffic alerts, public transport, and restaurant recommendations — all proactively.',
    color: '#9B59B6',
    price: 9.99,
    status: 'coming_soon',
    alwaysIncluded: false,
    capabilities: [
      { icon: '✈️', name: 'Flights', description: 'Search and track flights in real time' },
      { icon: '🏨', name: 'Hotels', description: 'Hotel search and booking assistance' },
      { icon: '🚦', name: 'Traffic', description: 'Live traffic alerts and route optimization' },
      { icon: '🚇', name: 'Transport', description: 'Public transport schedules and disruptions' },
      { icon: '🍽️', name: 'Restaurants', description: 'Restaurant recommendations by context' },
      { icon: '🚶', name: 'Leaving Now', description: 'Proactive alerts for when to leave' },
    ],
  },
  {
    id: 'ayvu',
    name: 'AYVU',
    fullName: 'AYVU — Voice & Media',
    description: 'Your voice and entertainment hub.',
    longDescription:
      'AYVU gives CAPIVAREX a real voice. Make phone calls, control your music, cast to your TV, and let ARA speak to you through ElevenLabs premium voice.',
    color: '#E91E8C',
    price: 14.99,
    status: 'coming_soon',
    alwaysIncluded: false,
    capabilities: [
      { icon: '📞', name: 'Phone Calls', description: 'Make and receive calls via Twilio' },
      { icon: '🎵', name: 'Music', description: 'Spotify control with mood-based playlists' },
      { icon: '📺', name: 'Cast to TV', description: 'Chromecast content to any screen' },
      { icon: '🎙️', name: 'Premium Voice', description: 'ElevenLabs voice for a human-like ARA' },
    ],
  },
  {
    id: 'mbae',
    name: 'MBAE',
    fullName: 'MBAE — Work & Productivity',
    description: 'Your professional assistant.',
    longDescription:
      'MBAE handles your professional life. Email management, GitHub integration, dev tools, and Notion — all orchestrated by ARA.',
    color: '#E67E22',
    price: 9.99,
    status: 'coming_soon',
    alwaysIncluded: false,
    capabilities: [
      { icon: '📧', name: 'Email Management', description: 'Full Gmail & Outlook control: AI drafts, inbox management, send replies, auto follow-ups' },
      { icon: '💻', name: 'Dev Tools', description: 'Code snippets, documentation lookup' },
      { icon: '🐙', name: 'GitHub', description: 'PR reviews, issue tracking, repo insights' },
      { icon: '📋', name: 'Notion', description: 'Notion pages and database management' },
    ],
  },
  {
    id: 'pora',
    name: 'PORA',
    fullName: 'PORA — Vision & Creative',
    description: 'Your creative studio.',
    longDescription:
      'PORA transforms CAPIVAREX into a creative powerhouse. Generate images, create videos, and bring your ideas to life through AI.',
    color: '#1ABC9C',
    price: 9.99,
    status: 'disabled',
    alwaysIncluded: false,
    capabilities: [
      { icon: '🎨', name: 'Image Generation', description: 'AI-powered image creation from text' },
      { icon: '🎬', name: 'Video Creation', description: 'Short video generation and editing' },
    ],
  },
  {
    id: 'tupa',
    name: 'TUPA',
    fullName: 'TUPA — Security Intelligence',
    description: 'Your invisible guardian.',
    longDescription:
      'TUPA monitors your account 24/7, detects threats, and alerts you when something is wrong. Security reports, session management, and auto-fix for low-severity threats.',
    color: '#DC2626',
    price: 89.99,
    status: 'active',
    alwaysIncluded: false,
    capabilities: [
      { icon: '🛡️', name: 'Threat Detection', description: 'Real-time monitoring of suspicious login attempts and anomalies' },
      { icon: '🔔', name: 'Security Alerts', description: 'Instant notifications when your account is at risk' },
      { icon: '📊', name: 'Weekly Security Report', description: 'Summary of events, blocked threats and account health' },
      { icon: '🔐', name: 'Session Management', description: 'View and revoke active sessions across all devices' },
      { icon: '🤖', name: 'Auto-fix', description: 'Automatic response to low-severity threats (Ultimate exclusive)' },
    ],
  },
];
